-- Seed initial projects from content.json
insert into public.projects
  (no, org, cjk, kind, img, href, tags, role, year, name,
   desc_cat, desc_es, desc_en, long_cat, long_es, long_en, sort_order)
values
  ('NM·01','DUCKHATS','寿司','BACKEND / API','p1.png',
   'https://github.com/DuckHats/backend-landing-sushi',
   ARRAY['PHP','Backend','API'],'Backend','2024','Sushi Landing',
   'Backend per a la landing d''un restaurant de sushi.',
   'Backend para la landing de un restaurante de sushi.',
   'Backend for a sushi restaurant landing page.',
   'Backend que dóna servei a la landing d''un restaurant de sushi — endpoints, gestió de dades i integració amb el front-end.',
   'Backend que da servicio a la landing de un restaurante de sushi — endpoints, gestión de datos e integración con el front-end.',
   'Server-side backend powering the landing site of a sushi restaurant — endpoints, data handling and integration with the front-end.',
   1),
  ('NM·02','DUCKHATS','出前','WEB / PRODUCT','p2.png',
   'https://github.com/DuckHats/demo-food4ducks-front',
   ARRAY['HTML','UI','Web'],'Front-end','2024','food4ducks',
   'Demo de front-end d''un producte de comandes de menjar.',
   'Demo de front-end de un producto de pedidos de comida.',
   'Food-ordering product front-end demo.',
   'Demo de front-end per a un producte de comandes de menjar: navegació de menú, flux de cistella i una interfície de comanda neta.',
   'Demo de front-end para un producto de pedidos de comida: navegación de menú, flujo de carrito y una interfaz de pedido limpia.',
   'Front-end demo for a food-ordering product: menu browsing, cart flow and a clean ordering UI.',
   2),
  ('NM·03','DUCKHATS','競走','WEB / FRONTEND','p3.png',
   'https://github.com/DuckHats/web_udg_racing_front',
   ARRAY['TypeScript','Frontend','Web'],'Front-end','2024','UdG Racing',
   'Front-end per al web de l''equip UdG Racing.',
   'Front-end para la web del equipo UdG Racing.',
   'Front-end for the UdG Racing team website.',
   'Front-end oficial de l''equip UdG Racing — presenta l''equip, el cotxe i la temporada en un lloc ràpid i responsive.',
   'Front-end oficial del equipo UdG Racing — presenta el equipo, el coche y la temporada en un sitio rápido y responsive.',
   'Official front-end for the UdG Racing team — presenting the team, the car and the season in a fast, responsive site.',
   3),
  ('NM·04','DUCKHATS','帽子','AI / HACKATHON','p4.png',
   'https://github.com/DuckHats/UVLHackEPS2025',
   ARRAY['PHP','AI','Web'],'Full-stack / AI','2025','UVLHackEPS2025',
   'App web d''IA — un "Barret Seleccionador" que classifica els barris de Los Angeles.',
   'App web de IA — un "Sombrero Seleccionador" que clasifica los barrios de Los Ángeles.',
   'AI web app — a "Sorting Hat" that classifies the neighborhoods of Los Angeles.',
   'Projecte de hackató: una app web amb IA, un "Barret Seleccionador" que classifica els barris de Los Angeles a partir de l''entrada de l''usuari.',
   'Proyecto de hackathon: una app web con IA, un "Sombrero Seleccionador" que clasifica los barrios de Los Ángeles a partir de la entrada del usuario.',
   'Hackathon project: an AI ''Sorting Hat'' web app that classifies the neighborhoods of Los Angeles from user input.',
   4),
  ('NM·05','PERSONAL','温度','HARDWARE / IOT','p5.png',
   'https://github.com/SergiGiribet/GineryPI',
   ARRAY['JavaScript','IoT','Raspberry Pi'],'Hardware / IoT','2024','GineryPI',
   'Sistema de control de temperatura sobre una Raspberry Pi.',
   'Sistema de control de temperatura sobre una Raspberry Pi.',
   'Temperature control system running on a Raspberry Pi.',
   'Un sistema de control de temperatura sobre una Raspberry Pi — llegeix sensors i actua segons llindars en temps real.',
   'Un sistema de control de temperatura sobre una Raspberry Pi — lee sensores y actúa según umbrales en tiempo real.',
   'A temperature-control system running on a Raspberry Pi — reading sensors and acting on thresholds in real time.',
   5),
  ('NM·06','PERSONAL','認証','EXPERIMENT','p6.png',
   'https://github.com/SergiGiribet/google-SignIn',
   ARRAY['HTML','Auth','Security'],'Auth / Security','2023','google-SignIn',
   'Experiment d''autenticació i seguretat.',
   'Experimento de autenticación y seguridad.',
   'Authentication & security experiment.',
   'Un experiment que explora fluxos d''autenticació i seguretat, inclosa la integració de Google Sign-In.',
   'Un experimento que explora flujos de autenticación y seguridad, incluida la integración de Google Sign-In.',
   'An experiment exploring authentication and security flows, including Google Sign-In integration.',
   6)
on conflict do nothing;
